
export interface IProduct {
	productId?: number;
	created_at?: number,
	description?: string,
	ean?: string,
	features?: Object,
	geo?: string[],
	gtins?: string[],
	height?: number,
	images_total?: number,
	length?: number,
	manufacturer?: string,
	messages?: string[],
	title?: string,
	thumbnail?: string,
	price?: number,
	price_currency?: string,
	sem3_id?: string,
	sitedetails?: Object[],
	upc?: string,
	updated_at?: number,
	weight?: number,
	width?: number,
	quantity?: number,
	brand?: string,
	category?: string,
	savings?: any,
	offers?: String[],
	picture?: string,
	rating?: number,
	images?: object,
	vendorsPrice?: number[],
	vendor?: string
}
